
- name: 'be sure homebrew packages is installed'
  homebrew: name={{ item.name }} state={{ item.state|default("latest") }} install_options={{ item.install_options|default() }}
  with_items:
    - { name: neovim }
    - { name: tmux }
    - { name: tig }
    - { name: go }
    - { name: peco }
    - { name: ghq }
    - { name: ctags }
    - { name: ag }
    - { name: direnv }
    - { name: jq }
    - { name: wget }
    - { name: rbenv }
    - { name: ruby-build }
    - { name: awscli }
    - { name: packer }
#    - { name: terraform }
    - { name: tfenv }

