---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  tasks:

    - name: 'be sure homebrew is updated'
      homebrew: update_homebrew=yes

    - include: tasks/brew-package.yml
    - include: tasks/brew-cask-package.yml

    - name: 'be sure gitsubmodule is initialized'
      command: git submodule update --init

    - name: 'be sure dotfiles is linked'
      file: src=~/dotfiles/dotfiles/{{ item.name }} dest=~/{{ item.dest_name if item.dest_name is defined else item.name }} state=link force=yes
      with_items:
        - { name: '.vimrc' }
        - { name: '.vim' }
        - { name: '.config/nvim' }
        - { name: '.tmux.conf' }
        - { name: '.tmux' }
        - { name: '.screenrc' }
        - { name: '.config/fish/fishfile' }
        - { name: '.config/fish/config.fish' }
        - { name: '.config/fish/env.fish' }
        - { name: '.config/fish/func.fish' }

